# -*- coding: utf-8 -*-
"""LLM Finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWO2AcEFWWowjF4TGMftn_LQgE_2EJGe
"""

import torch
torch.cuda.empty_cache()

!pip install transformers datasets accelerate peft bitsandbytes trl fsspec==2025.7.0

import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import get_peft_model, LoraConfig, TaskType, prepare_model_for_kbit_training

USE_GPU = torch.cuda.is_available()
DEVICE = "cuda" if USE_GPU else "cpu"

print("Using device:", DEVICE)

# Load model & tokenizer
model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=True)
model = AutoModelForCausalLM.from_pretrained(model_id, trust_remote_code=True, torch_dtype=torch.float16 if USE_GPU else torch.float32, device_map="auto")

data = [
    {
        "instruction": "I have a sore throat.",
        "response": "Gargle with warm salt water, drink warm fluids like tea with honey, and avoid cold drinks. If it lasts more than a few days, consult a doctor."
    },
    {
        "instruction": "I have a headache.",
        "response": "Rest in a quiet, dark room, stay hydrated, and take a mild pain reliever like paracetamol if needed. Avoid stress and bright screens."
    },
    {
        "instruction": "I have a cold.",
        "response": "Drink warm fluids, rest well, use steam inhalation, and take vitamin C. Avoid cold weather exposure."
    },
    {
        "instruction": "I have a fever.",
        "response": "Stay hydrated, rest, and take paracetamol if temperature is high. Use a cool damp cloth on your forehead to reduce heat."
    },
    {
        "instruction": "I feel dizzy.",
        "response": "Sit or lie down immediately, drink water, and avoid sudden movements. Eat something light if you haven’t eaten in a while."
    },
    {
        "instruction": "I have a cough.",
        "response": "Drink warm water with honey, use steam inhalation, and avoid cold or oily foods. If cough persists more than a week, see a doctor."
    },
    {
        "instruction": "I have stomach pain.",
        "response": "Drink warm water, eat light foods, avoid spicy and oily meals, and rest. If pain is severe or continues, consult a doctor."
    },
    {
        "instruction": "I feel bloated.",
        "response": "Avoid carbonated drinks, eat smaller meals, reduce salt intake, and go for a light walk after eating."
    },
    {
        "instruction": "I have a backache.",
        "response": "Apply a warm compress, maintain proper posture, do gentle stretching, and avoid lifting heavy objects."
    },
    {
        "instruction": "I have a toothache.",
        "response": "Rinse your mouth with warm salt water, apply a cold compress outside the cheek, and avoid sweet foods until you see a dentist."
    },
    {
        "instruction": "I feel tired all the time.",
        "response": "Get enough sleep, stay hydrated, eat a balanced diet with fruits and vegetables, and avoid excessive caffeine."
    },
    {
        "instruction": "I have an earache.",
        "response": "Apply a warm compress to the ear, avoid poking inside, and keep the ear dry. If pain persists, visit a doctor."
    },
    {
        "instruction": "I have diarrhea.",
        "response": "Drink plenty of oral rehydration solution (ORS), eat plain rice or bananas, and avoid oily or spicy food."
    },
    {
        "instruction": "I am constipated.",
        "response": "Eat high-fiber foods like fruits and vegetables, drink more water, and do light exercise daily."
    },
    {
        "instruction": "I have muscle cramps.",
        "response": "Stretch the affected muscle, massage gently, apply a warm compress, and stay hydrated with electrolyte-rich drinks."
    },
    {
        "instruction": "I feel nauseous.",
        "response": "Take small sips of water, eat bland foods like crackers or rice, and avoid strong smells. Rest in an upright position."
    },
    {
        "instruction": "I have chest tightness.",
        "response": "Sit down and rest, avoid physical activity, and take slow deep breaths. Seek medical help immediately if pain is severe or spreading."
    },
    {
        "instruction": "I feel short of breath.",
        "response": "Sit upright, stay calm, and avoid exertion. If breathing difficulty worsens or occurs suddenly, seek emergency care."
    },
    {
        "instruction": "I have joint pain.",
        "response": "Rest the affected joint, apply warm or cold compresses, and avoid strenuous movement. Consult a doctor if pain persists."
    },
    {
        "instruction": "I feel anxious.",
        "response": "Practice deep breathing, reduce caffeine intake, and try relaxation techniques. Seek professional help if anxiety affects daily life."
    },
    {
        "instruction": "I have difficulty sleeping.",
        "response": "Maintain a regular sleep schedule, avoid screens before bedtime, and keep your sleeping environment quiet and dark."
    },
    {
        "instruction": "I feel numbness in my hands.",
        "response": "Change posture, stretch your hands, and avoid repetitive strain. If numbness continues, consult a doctor."
    },
    {
        "instruction": "I have frequent urination.",
        "response": "Drink enough water, avoid caffeine, and monitor symptoms. See a doctor if urination is painful or excessive."
    },
    {
        "instruction": "I have swelling in my legs.",
        "response": "Elevate your legs, reduce salt intake, and avoid standing for long periods. Seek medical help if swelling is sudden or painful."
    },
    {
        "instruction": "I feel heart palpitations.",
        "response": "Sit down, relax, and avoid caffeine or stress. Consult a doctor if palpitations are frequent or accompanied by dizziness."
    },
    {
        "instruction": "I have eye strain.",
        "response": "Rest your eyes, follow the 20-20-20 rule, and reduce screen brightness. Use proper lighting while working."
    },
    {
        "instruction": "I feel pressure around my sinuses.",
        "response": "Use steam inhalation, stay hydrated, and apply warm compresses to the face. Consult a doctor if pain worsens."
    },
    {
        "instruction": "I have skin itching.",
        "response": "Avoid scratching, keep the skin moisturized, and avoid harsh soaps. Seek medical advice if itching persists."
    },
    {
        "instruction": "I feel burning while urinating.",
        "response": "Drink plenty of water and maintain proper hygiene. Consult a doctor as it may indicate an infection."
    },
    {
        "instruction": "I feel weak after illness.",
        "response": "Rest adequately, eat nutritious foods, and gradually return to activity. See a doctor if weakness continues."
    },
     {
        "instruction": "I have a runny nose.",
        "response": "Stay hydrated, use steam inhalation, and keep your nose clean. Avoid cold air and allergens."
    },
    {
        "instruction": "I feel chills and shivering.",
        "response": "Keep yourself warm, rest well, and drink warm fluids. Consult a doctor if chills continue with fever."
    },
    {
        "instruction": "I have pain while swallowing.",
        "response": "Drink warm liquids, avoid spicy foods, and rest your throat. See a doctor if swallowing becomes very painful."
    },
    {
        "instruction": "I feel pressure in my ears.",
        "response": "Swallow or yawn to relieve pressure and avoid sudden altitude changes. Consult a doctor if pain persists."
    },
    {
        "instruction": "I have leg pain after walking.",
        "response": "Rest your legs, stretch gently, and stay hydrated. Seek medical advice if pain occurs regularly."
    },
    {
        "instruction": "I feel excessive sweating.",
        "response": "Wear breathable clothing, stay hydrated, and manage stress. Consult a doctor if sweating occurs without exertion."
    },
    {
        "instruction": "I have dryness in my mouth.",
        "response": "Drink water frequently, chew sugar-free gum, and avoid caffeine. See a doctor if dryness persists."
    },
    {
        "instruction": "I feel pain in my lower abdomen.",
        "response": "Rest, drink warm water, and avoid heavy meals. Consult a doctor if pain is severe or persistent."
    },
    {
        "instruction": "I have ringing in my ears.",
        "response": "Avoid loud noises, reduce caffeine intake, and rest. Seek medical help if ringing continues."
    },
    {
        "instruction": "I feel burning in my chest after meals.",
        "response": "Avoid spicy or oily foods, eat smaller meals, and do not lie down immediately after eating."
    },
    {
        "instruction": "I have swelling around my eyes.",
        "response": "Apply a cold compress, reduce salt intake, and get enough sleep. Consult a doctor if swelling worsens."
    },
    {
        "instruction": "I feel shaky in my hands.",
        "response": "Rest, avoid caffeine, and eat balanced meals. Consult a doctor if shaking continues."
    },
    {
        "instruction": "I have pain in my neck.",
        "response": "Apply warm compresses, maintain good posture, and do gentle stretching exercises."
    },
    {
        "instruction": "I feel frequent yawning.",
        "response": "Ensure adequate sleep, stay hydrated, and take breaks during long work hours."
    },
    {
        "instruction": "I have itchy eyes.",
        "response": "Avoid rubbing your eyes, rinse with clean water, and reduce exposure to allergens."
    },
    {
        "instruction": "I feel tightness in my shoulders.",
        "response": "Stretch gently, apply warm compresses, and avoid prolonged sitting in one position."
    },
    {
        "instruction": "I have loss of appetite.",
        "response": "Eat small nutritious meals, stay hydrated, and avoid stress. Consult a doctor if appetite does not improve."
    },
    {
        "instruction": "I feel pain in my heels.",
        "response": "Rest your feet, wear comfortable footwear, and avoid prolonged standing."
    },
    {
        "instruction": "I have frequent burping.",
        "response": "Eat slowly, avoid carbonated drinks, and avoid overeating."
    },
    {
        "instruction": "I feel heaviness in my head.",
        "response": "Rest in a quiet place, stay hydrated, and avoid sudden movements."
    }
]


# Prepare dataset: format Q&A into instruction-response text
dataset = Dataset.from_list(data)

def format_prompt(example):
    return {
        "text": f"Instruction: {example['instruction']}\nResponse: {example['response']}"
    }

dataset = dataset.map(format_prompt)
dataset = dataset.remove_columns([col for col in dataset.column_names if col != "text"])

model = prepare_model_for_kbit_training(model)

# Configure and apply LoRA for causal language modeling
lora_config = LoraConfig(
    r=8, # Rank of low-rank matrices (smaller r → fewer trainable params, faster training)
    lora_alpha=16, # Scaling factor to control the impact of LoRA updates
    target_modules=["q_proj","v_proj","k_proj","o_proj"], # Specific transformer layers where LoRA is applied
    lora_dropout=0.05,  # Dropout applied to LoRA layers for regularization
    bias="none",  # Whether to train bias terms ("none", "all", or "lora_only")
    task_type=TaskType.CAUSAL_LM # Task type, here set for Causal Language Modeling
)
model = get_peft_model(model, lora_config)

# Prepares tokenized dataset for training by applying the tokenizer with truncation and padding
from transformers import TrainingArguments, Trainer, DataCollatorForLanguageModeling

tokenized_dataset = dataset.map(
    lambda x: tokenizer(x['text'], truncation=True, padding="max_length", max_length=256),
    batched=True
)

args = TrainingArguments(
    output_dir="./tinyllama-finetune",      # Folder where the trained model files will be stored
    num_train_epochs=6,                     # How many times the model will learn from the full dataset
    per_device_train_batch_size=1,          # How many training examples the model sees at one time
    gradient_accumulation_steps=2,          # Combine learning from 2 steps before updating the model (acts like training with 2 samples together)
    learning_rate=1e-4,                     # Speed at which the model learns (lower = safer learning)
    fp16=USE_GPU,                           # Use faster training on GPU (ignored on CPU)
    bf16=False,                             # Do not use bfloat16 precision
    optim="adamw_torch",                    # Method used to improve the model during training
    logging_steps=5,                        # Show training progress after every 5 steps
    save_steps=50,                          # Save the model every 50 steps
    save_total_limit=2,                     # Keep only the last 2 saved versions of the model
    report_to="none"                        # Do not send training logs to external tools
)

trainer = Trainer(
    model=model,   # The model being fine-tuned (LoRA-applied TinyLlama here)
    args=args,     # The training arguments defined above
    train_dataset=tokenized_dataset,   # Training data after tokenization
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False)
)

trainer.train()

# Move model to CPU before saving
model.to("cpu")

model.save_pretrained("med_finetuned")
tokenizer.save_pretrained("med_finetuned")

# Compress the 'med_finetuned' folder into 'med_finetuned.zip' (recursive, includes all files/subfolders)
!zip -r med_finetuned.zip med_finetuned

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from peft import PeftModel

model_path = "/content/med_finetuned"
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Load the base model first
base_model_id = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
base_model = AutoModelForCausalLM.from_pretrained(base_model_id, trust_remote_code=True, torch_dtype=torch.float16, device_map="auto")

# Load the PEFT model on top of the base model
model = PeftModel.from_pretrained(base_model, model_path)

model.eval()

def generate_response(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    with torch.no_grad():              # ensures no gradients (faster inference)
        outputs = model.generate(
            **inputs,
            max_new_tokens=500,        # how long the reply can be
            do_sample=True,            # enables sampling (not greedy)
            temperature=0.7,           # creativity (lower = more focused, higher = more random)
            top_p=0.9,                 # nucleus sampling (limits to top 90% probability mass)
            repetition_penalty=1.2,    # avoids repeating same words
            eos_token_id=tokenizer.eos_token_id   # stops generation at EOS
        )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

while True:
    user_input = input("Enter your symptoms (or type 'exit' to quit): ")

    if user_input.lower() == "exit":
        break

    prompt = f"### Instruction:\nQ: {user_input}\n\n### Response:\n"
    response = generate_response(prompt)

    # Extract only after "### Response:" to keep output clean
    clean_response = response.split("### Response:")[-1].strip()

    print("\nDiagnosis Suggestion:", clean_response, "\n")